## Reading data

In [ ]:
import pandas as pd
import numpy as np
import altair as alt

df = pd.read_csv("results.csv")
# Amount of entries before removing non-finished results
print(len(df))
df = df[df["elapsed"].notna()]
# Amount of entries that actually finished processing
print(len(df))
df.head()

41933
5088

   algorithm  max_a  max_b  block_size  block_amount  r  elapsed
2      Lars2   1000   1000           2             2  1     86.0
10     Lars2   1000    100           2             2  1     83.0
18     Lars2   1000     10           2             2  1     75.0
20     Gupta   1000     10           2             2  1   2320.0
22     Lars2   1000     10           4             4  1   9981.0

#### Results grouped by a single attribute

In [ ]:
inputs = ["max_a", "max_b", "block_size", "r"]

for x in inputs:
    chart = alt.Chart(df).mark_point().encode(
        x=alt.X(f"{x}:Q", title=x, scale=alt.Scale(type="log")),
        y=alt.Y(
            "elapsed:Q",
            title="Elapsed",
            scale=alt.Scale(type="log")
        ),
        color="algorithm:N",
        tooltip=inputs + ["elapsed", "algorithm"]
    ).properties(title=f"Elapsed vs {x}")

    display(chart)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

alt.Chart(...)

#### Summarized statistics

In [34]:
stats = (
    df.groupby(["algorithm", "r"])["elapsed"]
      .agg(
          count="count",
          mean="mean",
          median="median",
          std="std",
          min="min",
          max="max"
      )
      .reset_index()
)
# Filter for more than 1 result
stats = stats[stats["count"] > 30]
stats

,algorithm,r,count,mean,median,std,min,max
0,Gupta,1,713,7.004670e+03,1719.0,2.162265e+04,67.0,318130.0
1,Gupta,2,123,2.214457e+04,4789.0,6.789472e+04,233.0,492071.0
7,Lars1,1,265,1.316782e+05,108.0,9.500808e+05,24.0,11428066.0
8,Lars1,2,134,8.550966e+05,160.0,3.021004e+06,34.0,17329681.0
9,Lars1,3,70,5.364571e+02,269.0,7.390152e+02,39.0,3779.0
15,Lars2,1,792,2.396893e+03,592.0,6.784533e+03,26.0,95532.0
16,Lars2,2,298,7.050644e+03,94.0,4.814036e+04,52.0,697078.0
17,Lars2,3,220,2.785409e+02,74.0,9.578857e+02,49.0,6522.0
18,Lars2,4,204,1.089510e+02,73.0,1.732967e+02,48.0,1324.0
19,Lars2,5,221,1.308235e+02,75.0,3.470445e+02,47.0,4560.0
20,Lars2,6,221,1.245837e+02,79.0,2.210323e+02,52.0,2033.0
21,Lars2,7,221,1.072715e+02,78.0,1.439630e+02,53.0,1623.0
22,Lars2,8,221,9.974661e+01,76.0,1.355844e+02,33.0,1263.0
23,Lars2,9,221,1.087738e+02,79.0,1.647383e+02,54.0,1564.0
24,Lars2,10,221,9.345701e+01,77.0,9.534680e+01,54.0,939.0
25,Lis,1,625,7.679589e+05,32134.0,2.204941e+06,47.0,16872890.0
26,Lis,2,194,2.322606e+06,424870.5,3.692466e+06,122.0,17232542.0
27,Lis,3,42,2.799930e+06,115323.5,4.951554e+06,4210.0,17410228.0

In [ ]:
median_chart = alt.Chart(stats).mark_point(size=80).encode(
    x=alt.X("r:O", title="r"),
    y=alt.Y(
        "median:Q",
        title="Median elapsed",
        scale=alt.Scale(type="log")
    ),
    color=alt.Color("algorithm:N", title="Algorithm"),
    tooltip=[
        "algorithm",
        "r",
        "count",
        "mean",
        "median",
        "std",
        "min",
        "max"
    ]
).properties(title="Median elapsed time by algorithm and r")


mean_chart = alt.Chart(stats).mark_point(size=80).encode(
    x=alt.X("r:O", title="r"),
    y=alt.Y(
        "mean:Q",
        title="Mean elapsed",
        scale=alt.Scale(type="log")
    ),
    color=alt.Color("algorithm:N", title="Algorithm"),
    tooltip=[
        "algorithm",
        "r",
        "count",
        "mean",
        "median",
        "std",
        "min",
        "max"
    ]
).properties(title="Mean elapsed time by algorithm and r")

display(mean_chart)
display(median_chart)

alt.Chart(...)

alt.Chart(...)